import '../../core/models/feature_permissions.dart';
import '../../core/models/role_type.dart';
import '../../core/models/user_model.dart';

/// Read access to app users (staff). Backed by mock data in Sprint 1; a
/// Supabase implementation replaces it later without touching callers.
abstract interface class UserRepository {
  Future<List<UserModel>> getUsers();
  Future<UserModel?> getUserById(String id);
  Future<UserModel?> getUserByUsername(String username);

  /// Activate or deactivate a user. Returns the updated user, or null when the
  /// id is unknown. Mock-backed in this sprint.
  Future<UserModel?> setUserActive(String userId, bool active);

  /// Replace a user's [defaultRole] and full [roles] list. Returns the updated
  /// user, or null when the id is unknown or the default role isn't in [roles].
  /// Mock-backed in this sprint.
  Future<UserModel?> updateUserRoles(
    String userId, {
    required RoleType defaultRole,
    required List<RoleType> roles,
  });

  /// Replace a user's feature [permissions]. Returns the updated user, or null
  /// when the id is unknown. Mock-backed in this sprint.
  Future<UserModel?> updateUserPermissions(
    String userId,
    FeaturePermissions permissions,
  );

  /// Create a new user. The id is generated by the repository. Returns the
  /// created user, or null when [username] is already taken or [defaultRole]
  /// isn't in [roles]. Mock-backed in this sprint.
  Future<UserModel?> createUser({
    required String fullName,
    required String username,
    String? email,
    required RoleType defaultRole,
    required List<RoleType> roles,
    List<String> photoTypes,
    FeaturePermissions permissions,
    bool active,
  });

  /// Update a user's profile: identity, roles, photo types, and active flag.
  /// Permissions are managed separately. Returns the updated user, or null when
  /// the id is unknown, [username] collides with another user, or [defaultRole]
  /// isn't in [roles]. Mock-backed in this sprint.
  Future<UserModel?> updateUser(
    String userId, {
    required String fullName,
    required String username,
    String? email,
    required RoleType defaultRole,
    required List<RoleType> roles,
    List<String> photoTypes,
    bool active,
  });

  /// Permanently remove a user. Returns true when a user was removed, false
  /// when the id is unknown. Mock-backed in this sprint.
  Future<bool> deleteUser(String userId);
}
