-- =============================================================================
-- FIRST-ADMIN BOOTSTRAP — DEV ONLY, MANUAL, ONE-TIME. NOT a migration.
--
-- ⛔ Do NOT run against Production. ⛔ Do NOT commit real credentials/UUIDs.
-- This file contains PLACEHOLDERS only. It creates the FIRST administrator so the
-- admin-create-user flow (Step 10.2) has an admin to authenticate. There is no
-- "create by an admin" path for the very first admin, hence this manual step.
--
-- Canonical identity contract:
--   • login username (shown to users):        <ADMIN_USERNAME>   e.g. 'admin'
--   • normalized username (stored):            lower(trim(username)), ^[a-z0-9._-]{2,50}$
--   • hidden internal Auth email (auth.users): <normalized_username>@users.sumou.internal
--   • the internal email is NEVER shown in the app, NEVER in audit_logs, NEVER
--     returned by a public RPC.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- STEP A — create the Auth user in the DEV dashboard (NOT via SQL):
--   Dashboard → Authentication → Users → Add user
--     Email:    <normalized_username>@users.sumou.internal   (e.g. admin@users.sumou.internal)
--     Password: <choose a strong password>   (do NOT write it here)
--     ☑ Auto Confirm User
--   Copy the new user's UUID → paste as :admin_uid below. No password is stored here.
-- ---------------------------------------------------------------------------
-- \set admin_uid   '00000000-0000-0000-0000-000000000000'
-- \set admin_user  'admin'
-- \set admin_name  'إدارة سمو'

-- ---------------------------------------------------------------------------
-- STEP B — create the matching profile + admin role, in ONE transaction (the
-- deferrable default-role FK requires profile + user_role together). Run as the
-- postgres/service role in the DEV SQL editor.
--   • same UUID as the Auth user
--   • default_role_id = the active 'admin' role
--   • must_change_password: choose per your bootstrap decision:
--       - false  → the dashboard password is the admin's real password (default here)
--       - true   → treat the dashboard password as temporary; force a change on
--                  first login (once the Step-10.6 redirect exists)
--   • NO user_permissions rows are inserted — admin capability resolves from
--     role_permissions defaults (never copy role defaults into user_permissions).
-- ---------------------------------------------------------------------------
-- begin;
-- insert into public.profiles (id, username, full_name, default_role_id, is_active, must_change_password)
-- values (
--   :'admin_uid',
--   lower(btrim(:'admin_user')),
--   :'admin_name',
--   (select id from public.roles where code = 'admin' and is_active),
--   true,
--   false                                   -- bootstrap decision (see above)
-- );
-- insert into public.user_roles (user_id, role_id)
-- values (:'admin_uid', (select id from public.roles where code = 'admin' and is_active));
-- commit;

-- ---------------------------------------------------------------------------
-- STEP C — verify.
-- ---------------------------------------------------------------------------
-- select p.username, p.is_active, p.must_change_password,
--        (select array_agg(r.code) from public.user_roles ur
--           join public.roles r on r.id = ur.role_id where ur.user_id = p.id) as roles
-- from public.profiles p where p.id = :'admin_uid';
--   -- expect: username='admin', is_active=t, roles={admin}. Admin permissions
--   --         resolve via role_permissions (has_feature), not user_permissions.

-- ---------------------------------------------------------------------------
-- CLEANUP / RECOVERY (DEV only).
--   • wrong profile:   delete from public.user_roles where user_id = :'admin_uid';
--                      delete from public.profiles  where id      = :'admin_uid';
--                      then delete the Auth user in the dashboard.
--   • locked out:      dashboard → Authentication → reset the user's password;
--                      or re-run STEP B after cleanup.
--   • disable (keep history): update public.profiles set is_active = false where id = :'admin_uid';
--     (do NOT hard-delete auth.users for history; disabling fails closed in RLS.)
-- ---------------------------------------------------------------------------
