-- =============================================================================
-- Sprint 9 · Step 4 — Projects core schema
-- Domain: projects, project_team_members, project_team_types, project_stages
--         (+ the project_type / project_status / stage_status enums).
-- Runs AFTER:
--   20260714120000_identity_and_access.sql          (public.profiles, set_updated_at)
--   20260714130000_photographer_types_and_availability.sql (public.photographer_types)
--
-- Frozen decisions applied (see docs/SUPABASE_CORE_PLAN.md §1 / SCHEMA_DRAFT §4):
--   D1 manager owns the project (manager_id → profiles); roles resolve via Step 2
--   D3 normalized team: one project_team_members row per person, with 1..N types
--      in project_team_types referencing the photographer_types catalog (Step 3)
--   D6 soft delete on projects (is_active / deleted_at / deleted_by). Stages are
--      retained history (status changes, never deleted).
--
-- Guardrail (docs/BACKEND_SCOPE_GUARD.md): creates NO finance/payments/Rekaz/
-- notifications/FCM/push/reminders constructs. `project_team_members.value` is
-- assignment metadata only — it is NOT a fee, price, or any finance figure and
-- carries no finance behavior.
--
-- Scope (Step 4 ONLY): NO closure_requests, NO project_links, NO client_reviews,
-- and NO client-tracking tables/RPCs — those are Step 5. NO RLS policies, NO
-- RPCs, NO seed/reference rows, NO business logic (serial generation, stage
-- seeding, availability/overlap enforcement) — those belong to later RPC steps.
--
-- RLS: enabled on every table below with NO policies yet → default-deny for anon
-- and authenticated until Sprint 9 Step 6.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Enums (SCHEMA_DRAFT §1). Postgres enums for the closed, stable value sets.
-- Values mirror the Flutter keys exactly:
--   project_type   <- ProjectType   (field/social/wedding)
--   project_status <- ProjectStatus (active/in_progress/pending_closure/
--                                     completed/delivered/approved/rejected)
--   stage_status   <- ProjectStageStatus (pending/current/done)
-- The closure_status enum is intentionally NOT created here (Step 5).
-- ---------------------------------------------------------------------------
create type public.project_type as enum ('field', 'social', 'wedding');

create type public.project_status as enum (
  'active',
  'in_progress',
  'pending_closure',
  'completed',
  'delivered',
  'approved',
  'rejected'
);

create type public.stage_status as enum ('pending', 'current', 'done');

-- ---------------------------------------------------------------------------
-- projects (D6) — one row per project. `manager_id` is the owning manager
-- (used by the Step 6 manages_project() ownership check). `serial` is the
-- public, human-facing identifier (PREFIX-XXXX-XX, PREFIX ∈ FLD/SOC/WED),
-- unique and format-checked; it is GENERATED by the create_project RPC later,
-- not here. `manager_name` (app display field) is derived via a join/view.
-- ---------------------------------------------------------------------------
create table public.projects (
  id          uuid primary key default gen_random_uuid(),
  serial      text not null unique,
  name        text not null,
  client_name text not null,
  -- Owner. restrict: a profile that manages projects cannot be hard-removed out
  -- from under them (profiles are soft-deleted anyway, D6).
  manager_id  uuid not null references public.profiles (id) on delete restrict,
  type        public.project_type not null,
  status      public.project_status not null default 'active',
  start_date  date not null,
  end_date    date not null,
  notes       text,
  -- Soft delete (D6). is_active=false or deleted_at set → hidden by read policies.
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  deleted_at  timestamptz,
  deleted_by  uuid references public.profiles (id) on delete set null,
  -- Matches ProjectSerial exactly: 3-letter prefix (FLD/SOC/WED) + 4- and
  -- 2-char blocks over [A-Z0-9]. See lib/core/models/project_serial.dart.
  constraint projects_serial_format_chk
    check (serial ~ '^[A-Z]{3}-[A-Z0-9]{4}-[A-Z0-9]{2}$'),
  constraint projects_name_not_blank_chk check (char_length(btrim(name)) > 0),
  constraint projects_client_name_not_blank_chk check (char_length(btrim(client_name)) > 0),
  constraint projects_date_range_chk check (end_date >= start_date)
);
comment on table public.projects is
  'Projects (D6 soft delete). manager_id owns the project. serial is the public PREFIX-XXXX-XX identifier, generated by the create_project RPC (later).';
comment on column public.projects.serial is
  'Public human-facing identifier PREFIX-XXXX-XX (FLD/SOC/WED). Generated by RPC; unique + format-checked.';

create trigger projects_set_updated_at
  before update on public.projects
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- project_team_members (D3) — one row per assigned person per project. A member
-- may be an internal user (user_id set) or an external person (user_id null,
-- person_name only). Supports MULTIPLE members per project. `date` is the
-- assignment/shoot date the availability rules consult (is_available() in the
-- Step 6 RLS plan references t.date). `value` is assignment metadata only —
-- explicitly NOT finance.
-- ---------------------------------------------------------------------------
create table public.project_team_members (
  id          uuid primary key default gen_random_uuid(),
  project_id  uuid not null references public.projects (id) on delete cascade,
  -- null = external person (name only). set null: keep the team row if a profile
  -- is hard-removed (profiles are soft-deleted anyway, D6).
  user_id     uuid references public.profiles (id) on delete set null,
  person_name text not null,
  -- Assignment metadata only. NOT a fee / price / finance figure (guardrail).
  value       numeric not null default 0,
  -- Assignment/shoot date used by availability (overlap) checks. Nullable.
  date        date,
  constraint project_team_members_person_name_not_blank_chk
    check (char_length(btrim(person_name)) > 0)
);
comment on table public.project_team_members is
  'One row per assigned person per project (D3). user_id null = external person. value is assignment metadata ONLY, never finance.';
comment on column public.project_team_members.value is
  'Assignment metadata only — NOT a fee/price/finance figure. No finance behavior (guardrail).';

-- No duplicate internal photographer per project (only when user_id is set;
-- external people may repeat by name).
create unique index project_team_members_project_user_uidx
  on public.project_team_members (project_id, user_id)
  where user_id is not null;

-- ---------------------------------------------------------------------------
-- project_team_types (D3) — the photographer type(s) a given team member covers
-- on a project. MULTIPLE types per member (one row each), each referencing the
-- normalized photographer_types catalog (Step 3). This is what lets the app
-- aggregate back into one ProjectTeamRole per (person, type).
-- ---------------------------------------------------------------------------
create table public.project_team_types (
  id                   uuid primary key default gen_random_uuid(),
  team_member_id       uuid not null references public.project_team_members (id) on delete cascade,
  photographer_type_id uuid not null references public.photographer_types (id) on delete restrict,
  constraint project_team_types_member_type_uq
    unique (team_member_id, photographer_type_id)
);
comment on table public.project_team_types is
  'Photographer type(s) per team member (D3, M:N team_member <-> photographer_types). Multiple types per member allowed.';

-- ---------------------------------------------------------------------------
-- project_stages — the workflow stages of a project (retained history: statuses
-- change, rows are never deleted). Supports both the 3-stage and 7-stage
-- workflows: the number and titles of stages are DATA seeded per project by the
-- create_project RPC (later) — not fixed in the schema. `stage_order` is the
-- 1-based position (the app model's `order`; renamed because `order` is a
-- reserved SQL keyword). Unique per project. `updated_at` is set explicitly by
-- the stage-advance RPC (no auto-trigger) so it reflects real stage activity.
-- ---------------------------------------------------------------------------
create table public.project_stages (
  id          uuid primary key default gen_random_uuid(),
  project_id  uuid not null references public.projects (id) on delete cascade,
  title       text not null,
  stage_order int not null,
  status      public.stage_status not null default 'pending',
  notes       text,
  updated_by  uuid references public.profiles (id) on delete set null,
  updated_at  timestamptz,
  constraint project_stages_title_not_blank_chk check (char_length(btrim(title)) > 0),
  constraint project_stages_order_positive_chk check (stage_order >= 1),
  constraint project_stages_project_order_uq unique (project_id, stage_order)
);
comment on table public.project_stages is
  'Project workflow stages (retained history — never deleted). Stage count/titles are seeded per project by the create_project RPC (supports 3-stage and 7-stage flows). stage_order = app model order (renamed; order is reserved).';

-- ---------------------------------------------------------------------------
-- Indexes (SCHEMA_DRAFT §4.1/§4.2). Serial uniqueness is the constraint above;
-- these support ownership, filtering, availability, and soft-delete reads.
-- ---------------------------------------------------------------------------
create index projects_manager_idx      on public.projects (manager_id);
create index projects_status_idx       on public.projects (status);
create index projects_type_idx         on public.projects (type);
create index projects_dates_idx        on public.projects (start_date, end_date);
create index projects_active_idx       on public.projects (id) where deleted_at is null;

create index project_team_members_project_idx on public.project_team_members (project_id);
create index project_team_members_user_idx    on public.project_team_members (user_id);
create index project_team_members_date_idx     on public.project_team_members (date);

create index project_team_types_type_idx on public.project_team_types (photographer_type_id);

create index project_stages_project_idx on public.project_stages (project_id);

-- ---------------------------------------------------------------------------
-- Enable RLS (default-deny). NO policies yet → anon and authenticated have NO
-- access until Sprint 9 Step 6. No seed/reference data is inserted in this step.
-- ---------------------------------------------------------------------------
alter table public.projects             enable row level security;
alter table public.project_team_members enable row level security;
alter table public.project_team_types   enable row level security;
alter table public.project_stages       enable row level security;
